name: integration

on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    
jobs:
  docker:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v4
      with:
        node-version: 12.22.12

    - name: Check Node
      run: node --version

    - name: set environment
      run: cp .env.template .env

    - name: Start containers
      run: docker-compose up --detach

    - name: Wait a little
      run: sleep 10

    - name: Setup dev
      run: npm run setup:dev
